# Generated by Django 2.1b1 on 2019-01-05 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmzakat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('status', models.CharField(choices=[('LULUS', 'Lulus'), ('GAGAL', 'Gagal')], default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'confirmation',
            },
        ),
        migrations.CreateModel(
            name='Doczakat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=30, null=True)),
                ('icCopy', models.FileField(blank=True, null=True, upload_to='')),
                ('matricCopy', models.FileField(blank=True, null=True, upload_to='')),
                ('payslipCopy', models.FileField(blank=True, null=True, upload_to='')),
                ('resultCopy', models.FileField(blank=True, null=True, upload_to='')),
                ('debtstateCopy', models.FileField(blank=True, null=True, upload_to='')),
                ('mualafCopy', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Familyinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoKP', models.DecimalField(decimal_places=0, default=None, max_digits=12)),
                ('TelNo', models.DecimalField(decimal_places=0, default=None, max_digits=11)),
                ('Hubungan', models.CharField(choices=[('father', 'Bapa'), ('mum', 'Ibu'), ('stepFather', 'BapaTiri'), ('stepMum', 'IbuTiri'), ('gFather', 'Datuk'), ('gMother', 'Nenek'), ('guardian', 'Penjaga')], default=None, max_length=10)),
                ('Nama', models.CharField(default=None, max_length=100)),
                ('Rumah', models.CharField(choices=[('sendiri', 'SENDIRI'), ('sewa', 'SEWA')], default=None, max_length=10)),
                ('PekerjaanPenjaga', models.CharField(default=None, max_length=100)),
                ('PendapatanSebulan', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('PekerjaanPasanagan', models.CharField(default=None, max_length=100)),
                ('PendapatanSebulanPasangan', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('Pemohon', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('PendapatanKeluarga', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('SumbanganAnak', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('SumbanganDana', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('LainLain', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Formzakat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('icNo', models.DecimalField(decimal_places=0, default=None, max_digits=12)),
                ('body', models.TextField()),
                ('poskod', models.DecimalField(decimal_places=0, default=None, max_digits=5)),
                ('bandar', models.CharField(default=None, max_length=20)),
                ('noTel', models.DecimalField(decimal_places=0, default=None, max_digits=11)),
                ('DOB', models.CharField(default=None, max_length=20)),
                ('tLahir', models.CharField(default=None, max_length=20)),
                ('statusDiri', models.CharField(choices=[('bujang', 'Bujang'), ('berkahwin', 'Berkahwin'), ('duda', 'Duda'), ('janda', 'Janda')], default=None, max_length=10)),
                ('Kesihatan', models.CharField(choices=[('sihat', 'Sihat'), ('sakit', 'Sakit'), ('oku', 'OKU')], default=None, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ProgramPengajian', models.CharField(default=None, max_length=100)),
                ('Fakulti', models.CharField(choices=[('cvac', 'CVAC'), ('els', 'ELS'), ('fess', 'FESS'), ('fob', 'FOB'), ('cfgs', 'CFGS'), ('cgs', 'CGS')], default=None, max_length=10)),
                ('PeringkatPengajian', models.CharField(choices=[('asasi', 'Asasi'), ('diploma', 'Diploma'), ('degree', 'Ijazah'), ('master', 'Sarjana'), ('phd', 'PHD')], default=None, max_length=10)),
                ('TempohPengajian', models.DecimalField(decimal_places=1, default=None, max_digits=2)),
                ('CPGA', models.DecimalField(decimal_places=2, default=None, max_digits=3)),
                ('Penaja', models.CharField(default=None, max_length=100)),
                ('StatusPenaja', models.CharField(choices=[('ongoing', 'SedangDipohon'), ('received', 'SedangMenerima'), ('finished', 'Tamat'), ('suspended', 'Digantung')], default=None, max_length=15)),
                ('JumlahTajaan', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('NamaBank', models.CharField(default=None, max_length=100)),
                ('NoAkaun', models.CharField(default=None, max_length=30)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='familyinfo',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='formzakat.Formzakat'),
        ),
        migrations.AddField(
            model_name='doczakat',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formzakat.Formzakat'),
        ),
    ]
