# Generated by Django 2.1b1 on 2019-01-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icNo', models.DecimalField(decimal_places=0, default=None, max_digits=12)),
                ('status', models.CharField(choices=[('lulus', 'Lulus'), ('gagal', 'Gagal')], default=None, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
